import React, { useState } from "react";
import Carousel from "react-bootstrap/Carousel";
import Button from "react-bootstrap/Button";
import Modal from "react-bootstrap/Modal";

function Portfolio() {
  const [show, setShow] = useState(false);
  const [content, setContent] = useState("");
  const [Interval, setInterval] = useState(5000);

  const handleClose = () => {
    setShow(false);
    setContent("");
    setInterval(5000);
  };
  const handleShow = (event) => {
    setShow(true);
    const index = event.target.getAttribute("index");
    setContent({ ...photos[index], index: index });
    setInterval(1000000);
  };

  const photos = [
    {
      name: "Sub-Atomic",
      description:
        "A gig work style app designed to make it easier for administrators to find substitute teachers. Utilizes a message board where users can generate and edit profiles and apply to substitute teaching jobs. Admins can post and delete jobs and are alerted when they receive applicants. This is a fully functional single page application with authentication utilizing the MERN stack(MongoDB, Express.js, React.js, Node.js).",
      languages:
        "MongoDB, Express.js, React.js, Node.js, GraphQL, Apollo Server, Heroku, Bootstrap",
      repo: "https://github.com/eclevela-1234/Substitute-Finder",
      app: "https://sub-atomic-mern.herokuapp.com/",
    },
    {
      name: "Random Project Generator",
      description:
        "Mobile responsive front end app that utilizes local storage to save “projects” which are randomly generated by several public APIs. We come a long way since this but was super proud of the team for putting this together after about a month into the Full Stack Boot Camp.",
      languages: "HTML5, CSS3, JavaScript, Bulma",
      repo: "https://github.com/eclevela-1234/Random-Project-Generator",
      app: "https://eclevela-1234.github.io/Random-Project-Generator",
    },
    {
      name: "Business Metrics Dashboard",
      description:
        "An interactive dashboard created using Plotly.js to bring to life sales and weather data. This was a final project in the data analytics boot camp. Used Pandas to clean data and a variety of software packages for exploratory data analysis. As I dive back into business analytics, I plan to create web apps with similar utility but with authentication and a more responsive front end by applying concepts learned in the full stack program.",
      languages: "HTML5, CSS3, JavaScript, Python, Pandas, Excel, Tableau",
      repo: "https://github.com/eclevela-1234/Business-Metrics",
      app: "https://eclevela-1234.github.io/Business-Metrics",
    },
    {
      name: "Portfolio Designer",
      description:
        "A app where users can generate a formatted portfolio through a API request to GitHub. It is a little clunky and uses handlebars to render pages. Authentication functions as it should and allows access from anywhere. Room to grow but a valiant shot at a full stack application.",
      languages:
        "Node.js, Express.js, Handlebars, Sequelize, MySQL, BCrypt, HTML5, CSS3, JavaScript",
      repo: "https://github.com/eclevela-1234/portfolio-designer-2",
      app: "https://peaceful-reef-87519.herokuapp.com/login",
    },
    {
      name: "Express Note Taker",
      description:
        "A note taking app that uses API routes to update Create, Read, Update, and Delete a JSON file containing USER Notes. App is deployed to a Heroku Node envvironment",
      languages: "Node.js, Express.js, RESTful API, HTML5, CSS3, JavaScript",
      repo: "https://github.com/eclevela-1234/Express-Note-Taker",
      app: "https://agile-dawn-36237.herokuapp.com/",
    },
  ];
  return (
    <div>
      <h2 className="m-3">Portfolio</h2>
      <div className="row">
        <Carousel variant="dark rounded" className="col-md-8 m-auto">
          {photos.map((image, i) => (
            <Carousel.Item interval={Interval} key={i}>
              <img
                className="w-100 thumbnail border border-dark"
                src={require(`../../assets/images/${i}.png`)}
                alt={image.name}
              />
              <Carousel.Caption className="bg-light border border-dark rounded">
                <h3 className="fw-bold">{image.name}</h3>
                <p>
                  <strong>{image.languages}</strong>
                </p>
                <Button variant="primary" index={i} onClick={handleShow}>
                  Learn More
                </Button>
              </Carousel.Caption>
            </Carousel.Item>
          ))}
        </Carousel>
      </div>
      <Modal show={show} size="lg" onHide={handleClose}>
        <Modal.Header closeButton>
          <Modal.Title>{content.name}</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p>{content.description}</p>{" "}
          <p>
            <strong>{content.languages}</strong>
          </p>
          <a href={content.repo}>
            <Button variant="primary my-2">Repo</Button>
          </a>
          {content.app ? (
            <a href={content.app}>
              <Button variant="info mx-2">App</Button>
            </a>
          ) : (
            <></>
          )}
          <>
            {content.index ? (
              <img
                className="w-100 thumbnail"
                src={require(`../../assets/images/${content.index}.png`)}
                alt={"a"}
              />
            ) : (
              <></>
            )}
          </>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
}

export default Portfolio;
