import React, { useState } from "react";
import Carousel from "react-bootstrap/Carousel";
import Button from "react-bootstrap/Button";
import Modal from "react-bootstrap/Modal";
// import AppModal from "../../components/AppModal";

function Portfolio() {
  const [show, setShow] = useState(false);
  const [content, setContent] = useState("");

  const handleClose = () => {
    setShow(false);
    setContent("");
  };
  const handleShow = (event) => {
    setShow(true);
    const index = event.target.getAttribute("index");
    setContent({ ...photos[index], index: index });
  };

  const photos = [
    {
      name: "Sub-Atomic",
      description:
        "A gig work style app designed to make it easier for administrators to find substitute teachers. Utilizes a message board where users can generate and edit profiles and apply to substitute teaching jobs. Admins can post and delete jobs and are alerted when they receive applicants.",
      languages:
        "MongoDB, Express.js, React.js, Node.js, GraphQL, Apollo Server, Heroku",
      repo: "https://github.com/eclevela-1234/Substitute-Finder",
      app: "https://sub-atomic-mern.herokuapp.com/",
    },
    {
      name: "Random Project Generator",
      description:
        "Mobile responsive front end app that utilizes local storage to save “projects” which are randomly generated by several public APIs. Put together about a month into the Full Stack Boot Camp.",
      languages: "HTML5, CSS3, JavaScript",
      repo: "https://github.com/eclevela-1234/Random-Project-Generator",
      app: "https://eclevela-1234.github.io/Random-Project-Generator",
    },
    {
      name: "Express Note Taker",
      description:
        "A note taking app that uses API routes to update Create, Read, Update, and Delete a JSON file containing USER Notes. App is deployed to a Heroku Node envvironment",
      languages: "Node.js, Express.js, RESTful API, HTML5, CSS3, JavaScript",
      repo: "https://github.com/eclevela-1234/Express-Note-Taker",
      app: "https://agile-dawn-36237.herokuapp.com/",
    },
    {
      name: "Portfolio Designer",
      repo: "https://github.com/eclevela-1234/portfolio-designer-2",
      app: "https://peaceful-reef-87519.herokuapp.com/login",
    },
    {
      name: "My Team App",
      description: "",
      languages: "",
      repo: "https://github.com/eclevela-1234/My-Team-App",
      app: "",
    },
    {
      name: "Reactions",
      description: "",
      languages: "",
      repo: "https://github.com/eclevela-1234/Reactions",
      app: "",
    },
    {
      name: "Taskmaster Pro",
      description: "",
      languages: "",
      repo: "https://github.com/eclevela-1234/taskmaster-pro",
      app: "https://eclevela-1234.github.io/taskmaster-pro/",
    },
  ];
  return (
    <div>
      <h2 className="m-3">Portfolio</h2>
      <div className="row">
        <Carousel variant="dark" className="col-md-8 m-auto">
          {photos.map((image, i) => (
            <Carousel.Item interval={5000} key={i}>
              <img
                className="w-100 thumbnail"
                src={require(`../../assets/images/${i}.png`)}
                alt={image.name}
              />
              <Carousel.Caption className="bg-light border border-dark rounded">
                <h3 className="fw-bold">{image.name}</h3>
                <p>
                  <strong>Language/Technology</strong>
                  <br />
                  {image.languages}
                </p>
                <Button variant="primary" index={i} onClick={handleShow}>
                  Learn More
                </Button>
              </Carousel.Caption>
            </Carousel.Item>
          ))}
        </Carousel>
      </div>
      <Modal show={show} size="lg" onHide={handleClose}>
        <Modal.Header closeButton>
          <Modal.Title>{content.name}</Modal.Title>
        </Modal.Header>
        <Modal.Body><p>{content.description}</p>
          <a href={content.repo}><Button variant="primary my-2">Repo</Button></a>
        {content.app? (<a href={content.app}><Button variant="info mx-2">App</Button></a>) : (<></>)}
          <>
            {content.index ? (
              <img
                className="w-100 thumbnail"
                src={require(`../../assets/images/${content.index}.png`)}
                alt={"a"}
              />
            ) : (
              <div></div>
            )}
          </>
        </Modal.Body>
        <Modal.Footer>
        
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
}

export default Portfolio;
